// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Wt44QnqjFqsna5KQaqk2xlsFIJEHkYM',
    appId: '1:488350078513:android:f74a9bdb3704af4da9e710',
    messagingSenderId: '488350078513',
    projectId: 'tinytalesapp-4fe9d',
    databaseURL: 'https://tinytalesapp-4fe9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tinytalesapp-4fe9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwSbHfkixpEjrR4nslDBwdOwQpAoowH18',
    appId: '1:488350078513:ios:dc9c98ad58fa9baaa9e710',
    messagingSenderId: '488350078513',
    projectId: 'tinytalesapp-4fe9d',
    databaseURL: 'https://tinytalesapp-4fe9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tinytalesapp-4fe9d.firebasestorage.app',
    iosBundleId: 'com.example.tinytales',
  );

}